### ISSUE TITLE
Unable to add friends

### ISSUE THREAD

**Issue by SEBROVATER** [mrkaye97/medici#1]
Hi. 
I'm very curious about this project and am currently trying to self-host it behind *Caddy* reverse-proxy. I would possibly update deployment instructions, but now I have an issue with adding friends:

1) When I input the needed email and click "Send friend request," it fails with the message "**Failed to send friend request. Please try again.**"
In the browser, I see that there is a **502 Bad Gateway** error for this URL: `http://<my_ip>/api/friend-requests` POST request.
In the logs of the *server* container, I see this:
```Rust
thread 'tokio-runtime-worker' panicked at src/handlers.rs:782:14:
Failed to create friend request: NotFound
stack backtrace:
   0: __rustc::rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::result::unwrap_failed
   3: server::handlers::create_friend_request_handler::{{closure}}::{{closure}}
   4: tokio::runtime::task::core::Core<T,S>::poll
   5: tokio::runtime::task::harness::Harness<T,S>::poll
   6: tokio::runtime::blocking::pool::Inner::run
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

thread 'tokio-runtime-worker' panicked at src/handlers.rs:785:6:
Task panicked: JoinError::Panic(Id(175), "Failed to create friend request: NotFound", ...)
stack backtrace:
   0: __rustc::rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::result::unwrap_failed
   3: <F as axum::handler::Handler<(M,T1,T2),S>>::call::{{closure}}
   4: <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll
   5: <axum::util::MapIntoResponseFuture<F> as core::future::future::Future>::poll
   6: <tower::util::oneshot::Oneshot<S,Req> as core::future::future::Future>::poll
   7: <axum::routing::route::RouteFuture<E> as core::future::future::Future>::poll
   8: <axum::util::MapIntoResponseFuture<F> as core::future::future::Future>::poll
   9: <axum::middleware::from_fn::FromFn<F,S,I,(T1,)> as tower_service::Service<http::request::Request<axum_core::body::Body>>>::call::{{closure}}
  10: <axum::middleware::from_fn::ResponseFuture as core::future::future::Future>::poll
  11: <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll
  12: <axum::util::MapIntoResponseFuture<F> as core::future::future::Future>::poll
  13: <tower::util::oneshot::Oneshot<S,Req> as core::future::future::Future>::poll
  14: <tower_http::cors::ResponseFuture<F> as core::future::future::Future>::poll
  15: <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll
  16: <axum::util::MapIntoResponseFuture<F> as core::future::future::Future>::poll
  17: <tower::util::oneshot::Oneshot<S,Req> as core::future::future::Future>::poll
  18: <axum::routing::route::RouteFuture<E> as core::future::future::Future>::poll
  19: <hyper_util::service::oneshot::Oneshot<S,Req> as core::future::future::Future>::poll
  20: hyper::proto::h1::dispatch::Dispatcher<D,Bs,I,T>::poll_loop
  21: hyper::proto::h1::dispatch::Dispatcher<D,Bs,I,T>::poll_catch
  22: <hyper::server::conn::http1::UpgradeableConnection<I,S> as core::future::future::Future>::poll
  23: <hyper_util::server::conn::auto::UpgradeableConnection<I,S,E> as core::future::future::Future>::poll
  24: <core::future::poll_fn::PollFn<F> as core::future::future::Future>::poll
  25: axum::serve::WithGracefulShutdown<L,M,S,F>::run::{{closure}}::{{closure}}
  26: tokio::runtime::task::core::Core<T,S>::poll
  27: tokio::runtime::task::harness::Harness<T,S>::poll
  28: tokio::runtime::scheduler::multi_thread::worker::Context::run_task
  29: tokio::runtime::scheduler::multi_thread::worker::Context::run
  30: tokio::runtime::context::scoped::Scoped<T>::set
  31: tokio::runtime::context::runtime::enter_runtime
  32: tokio::runtime::scheduler::multi_thread::worker::run
  33: <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll
  34: tokio::runtime::task::core::Core<T,S>::poll
  35: tokio::runtime::task::harness::Harness<T,S>::poll
  36: tokio::runtime::blocking::pool::Inner::run
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```
In the logs of *db* or *frontend* container, I don't see anything wrong.

I suggest the core of this problem lies on my side because I have to tweak default configurations to make it more secure as a self-hosted thing. 

My current Caddy configuration (if that can help):
```.conf
<my_ip>:80 {

        @api path /api/*
        reverse_proxy @api 127.0.0.1:9277

        reverse_proxy 127.0.0.1:9274
        encode gzip
        log {
                output file /var/log/caddy/medici-access.log
        }
}
```
My updated `docker-compose.yaml` file:
```yaml
services:
  db:
    image: postgres:18
    environment:
      POSTGRES_USER: medici_user
      POSTGRES_PASSWORD: <secret_password>
      POSTGRES_DB: medici
    volumes:
      - data:/var/lib/postgresql
    expose:
      - "5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U medici_user -d medici"]
      interval: 5s
      timeout: 5s
      retries: 10

  server:
    image: mrkaye97/medici-server:latest
    env_file: ./.env
    ports:
      - "127.0.0.1:9277:8000"
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  frontend:
    image: mrkaye97/medici-frontend:latest
    env_file: ./.env
    ports:
      - "127.0.0.1:9274:3000"
    depends_on:
      - server
    restart: unless-stopped

volumes:
  data:
```
2) I'm personally actually okay with the inability to add real users to this service. It would be enough for me to just add `dummy` users, not real people. I would like to know if that is possible, because I currently can't fund this feature.

**Comment by mrkaye97** [comment]
wow, first issue! 🥳 

this just sounds like a bug - I think the API is panicking if the user who you are trying to add as a friend does not exist. I fixed this and am building new images!

**Comment by mrkaye97** [comment]
should be fixed - closing this! let me know if you keep having issues

**Comment by SEBROVATER** [comment]
Hello again. Actually, I’m still facing the same issue, with a small change.
Now the browser returns a 404 Not Found HTTP error for the POST request for the endpoint `/api/friend-requests`, and I don’t see any error logs in the containers. I also see the same 404 HTTP errors for these endpoints: `/api/members/me` and `/api/friends` which are called periodcally.

The configuration is exactly the same as before.
The strangest thing is that most requests are working, but some of them are not.

And I still have the same question: is it possible to add "dummy" friends to pools so that I could be the only manager for them?

**Comment by mrkaye97** [comment]
If you're seeing 404, it must be that the friend you're trying to add to the pool is not yet a member, so they don't exist

Re: dummy friends - sure, I don't see why not, but you'd need to make accounts for the dummy friends before you add them. Let me know if that helps

**Comment by SEBROVATER** [comment]
I definitely did not try to add a non-existent friend to the pool (not sure that it is even possible). More interestingly, I can't even create a pool. `server` shows this error log:
```log
server-1    |
server-1    | thread 'tokio-runtime-worker' panicked at src/handlers.rs:374:14:
server-1    | Failed to create pool membership: DatabaseError(ForeignKeyViolation, "insert or update on table \"pool_membership\" violates foreign key constraint \"pool_membership_member_id_fkey\"")
server-1    | stack backtrace:
server-1    |    0: __rustc::rust_begin_unwind
server-1    |    1: core::panicking::panic_fmt
server-1    |    2: core::result::unwrap_failed
server-1    |    3: server::handlers::create_pool_handler::{{closure}}::{{closure}}
server-1    |    4: tokio::runtime::task::core::Core<T,S>::poll
server-1    |    5: tokio::runtime::task::harness::Harness<T,S>::poll
server-1    |    6: tokio::runtime::blocking::pool::Inner::run
server-1    | note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
server-1    |
server-1    | thread 'tokio-runtime-worker' panicked at src/handlers.rs:377:6:
server-1    | Task panicked: JoinError::Panic(Id(29), "Failed to create pool membership: DatabaseError(ForeignKeyViolation, \"insert or update on table \\\"pool_membership\\\" violates foreign key constraint \\\"pool_membership_member_id_fkey\\\"\")", ...)
server-1    | stack backtrace:
server-1    |    0: __rustc::rust_begin_unwind
server-1    |    1: core::panicking::panic_fmt
server-1    |    2: core::result::unwrap_failed
server-1    |    3: <F as axum::handler::Handler<(M,T1,T2),S>>::call::{{closure}}
server-1    |    4: <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll
server-1    |    5: <axum::util::MapIntoResponseFuture<F> as core::future::future::Future>::poll
server-1    |    6: <tower::util::oneshot::Oneshot<S,Req> as core::future::future::Future>::poll
server-1    |    7: <axum::routing::route::RouteFuture<E> as core::future::future::Future>::poll
server-1    |    8: <axum::util::MapIntoResponseFuture<F> as core::future::future::Future>::poll
server-1    |    9: <axum::middleware::from_fn::FromFn<F,S,I,(T1,)> as tower_service::Service<http::request::Request<axum_core::body::Body>>>::call::{{closure}}
server-1    |   10: <axum::middleware::map_response::ResponseFuture as core::future::future::Future>::poll
server-1    |   11: <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll
server-1    |   12: <axum::util::MapIntoResponseFuture<F> as core::future::future::Future>::poll
server-1    |   13: <tower::util::oneshot::Oneshot<S,Req> as core::future::future::Future>::poll
server-1    |   14: <tower_http::cors::ResponseFuture<F> as core::future::future::Future>::poll
server-1    |   15: <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll
server-1    |   16: <axum::util::MapIntoResponseFuture<F> as core::future::future::Future>::poll
server-1    |   17: <tower::util::oneshot::Oneshot<S,Req> as core::future::future::Future>::poll
server-1    |   18: <axum::routing::route::RouteFuture<E> as core::future::future::Future>::poll
server-1    |   19: <hyper_util::service::oneshot::Oneshot<S,Req> as core::future::future::Future>::poll
server-1    |   20: hyper::proto::h1::dispatch::Dispatcher<D,Bs,I,T>::poll_loop
server-1    |   21: hyper::proto::h1::dispatch::Dispatcher<D,Bs,I,T>::poll_catch
server-1    |   22: <hyper::server::conn::http1::UpgradeableConnection<I,S> as core::future::future::Future>::poll
server-1    |   23: <hyper_util::server::conn::auto::UpgradeableConnection<I,S,E> as core::future::future::Future>::poll
server-1    |   24: <core::future::poll_fn::PollFn<F> as core::future::future::Future>::poll
server-1    |   25: axum::serve::WithGracefulShutdown<L,M,S,F>::run::{{closure}}::{{closure}}
server-1    |   26: tokio::runtime::task::core::Core<T,S>::poll
server-1    |   27: tokio::runtime::task::harness::Harness<T,S>::poll
server-1    |   28: tokio::runtime::scheduler::multi_thread::worker::Context::run_task
server-1    |   29: tokio::runtime::scheduler::multi_thread::worker::Context::run
server-1    |   30: tokio::runtime::context::scoped::Scoped<T>::set
server-1    |   31: tokio::runtime::context::runtime::enter_runtime
server-1    |   32: tokio::runtime::scheduler::multi_thread::worker::run
server-1    |   33: <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll
server-1    |   34: tokio::runtime::task::core::Core<T,S>::poll
server-1    |   35: tokio::runtime::task::harness::Harness<T,S>::poll
server-1    |   36: tokio::runtime::blocking::pool::Inner::run
server-1    | note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```
Also, I stay logged in even after a full recreation of containers with the removal of the database.

**Comment by mrkaye97** [comment]
what was the set of actions you took that caused this error? this looks similar, like trying to add someone to a pool who doesn't exist

**Comment by mrkaye97** [comment]
in any case, I can add some better error handling here to show something more helpful in the UI for these cases!
